alo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('disp.urls'))
]

disp/urls.py
from __future__ import unicode_literals
from django.urls import path
from . import views

app_name= 'disp'

urlpatterns = [
    path('', views.loginpage, name='loginpage'),
    path('home/(?P<name>\w+/(?P<password>\w+))/', views.index, name='index'),
    path('error', views.errorpage, name='errorpage'),
   

    
]

disp/models.py
from django.db import models

# Create your models here.


 

disp/forms.py
from django import forms

class loginForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id' : 't', 'placeholder': 'Name'}),label='')
    password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={ 'id': 'pass', 'placeholder': 'Password'}),label='')
class requet(forms.Form):
    req = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id' : 'req', 'placeholder': 'Requête'}),label='')
class result(forms.Form):
    rslt= forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id' : 'rslt', 'placeholder': 'rslt'}),label='')

 

disp/views.py
from django.shortcuts import render

# Create your views here.
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import Context, Template
from .forms import loginForm, requet, result
 
import cx_Oracle
 
        


def connection_db2(request,name,password):
           l = []
     
           db1 = cx_Oracle.connect(name, password, 'localhost:1521/orcl')
     
           try:
            dsn_tns = cx_Oracle.makedsn('localhost', 1521, 'orcl')
            cursor = db1.cursor()
           
            cursor.execute('selecht * form DEPARTMENTS')
            for row in cursor:
             print (row[0]) 
             l.append(row[0])
             return l
           except mysql.connector.Error as err:
             print('erroo',err) 
 
def connection_db(request,name,password):
    v= 0 
    try:
        db1 = cx_Oracle.connect(name, password, 'localhost:1521/orcl')
    except :
        v = 1 
        pass

        print('hii')
        #return redirect('disp:errorpage')
    #db1 = cx_Oracle.connect('hr/123456789@localhost:1521/orcl')
    l = []
    ll = []
    cl = []
    cll = []
    clll = []
    cllll = []
    clllll = []
 

    if not v:
        dsn_tns = cx_Oracle.makedsn('localhost', 1521, 'orcl')
        cursor = db1.cursor()
    
        cursor.execute('select table_name from user_tables')
        for row in cursor:
            print (row[0]) 
            l.append(row[0])

    
    
            c = db1.cursor()
            c.execute('select * from {0}'.format(row[0]))
            col_names = [row[0] for row in c.description]
            ll.append(col_names)
            print(col_names)

        c1 = db1.cursor()
        c1.execute('select view_name from user_views')
        for ro in c1:
         print (ro) 
         cl.append(ro[0])

        cll = db1.cursor()
        cll.execute('SELECT INDEX_NAME FROM USER_INDEXES')
         
        clll = db1.cursor()
        clll.execute('SELECT SEQUENCE_NAME FROM USER_SEQUENCES')
        cllll = db1.cursor()
        cllll.execute('SELECT PROCEDURE_NAME FROM USER_PROCEDURES')
        clllll = db1.cursor()
        clllll.execute('SELECT TRIGGER_NAME FROM USER_TRIGGERS')


  
    return l,ll,v,cl,cll,clll,cllll,clllll
 


    
    

def index(request, name, password):
    l = []
    tables, colunms, v, views, index, seq, tig, proc= connection_db(request,name, password)
    #return HttpResponse(tables)
    if v:
        return render(request, 'error.html')
      

    if request.method == "POST":
        form = requet(request.POST)
        if form.is_valid():
         reqeutsql = form.cleaned_data['req']
         print('data', reqeutsql)

         db1 = cx_Oracle.connect(name, password, 'localhost:1521/orcl')   
         dsn_tns = cx_Oracle.makedsn('localhost', 1521, 'orcl')
         cursor = db1.cursor()
        try:
         cursor.execute(reqeutsql)
         for row in cursor:
          l.append(row)
        except :
          l.append('vérifier votre requête')
        

    req = requet()
     
       

    return render(request, 'indexu.html' , {'tig' : tig, 'proc' : proc, 'seq' : seq, 'index' : index, 'tables' : tables, 'colunms' : colunms, 'req' : req, 'l' : l, 'views' : views})

 

def loginpage(request):
    if request.method == "POST":
        form = loginForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            password = form.cleaned_data['password']
            print('data', name , password)
            return redirect ('disp:index', name = name, password = password)
    else:
        form = loginForm()
    
    return render(request,'login.html',{'form' : form })


def errorpage(request):
    return render(request, 'error.html')



 

disp/templates/error.html
<!DOCTYPE html>
<html>
<head>

    <style>
    
    @import url(https://fonts.googleapis.com/css?family=opensans:500);
body{
                background: #33cc99;
                color:#fff;
                font-family: 'Open Sans', sans-serif;
                max-height:700px;
                overflow: hidden;
            }
            .c{
                text-align: center;
                display: block;
                position: relative;
                width:80%;
                margin:100px auto;
            }
            ._404{
                font-size: 220px;
                position: relative;
                display: inline-block;
                z-index: 2;
                height: 250px;
                letter-spacing: 15px;
            }
            ._1{
                text-align:center;
                display:block;
                position:relative;
                letter-spacing: 12px;
                font-size: 4em;
                line-height: 80%;
            }
            ._2{
                text-align:center;
                display:block;
                position: relative;
                font-size: 20px;
            }
            .text{
                font-size: 70px;
                text-align: center;
                position: relative;
                display: inline-block;
                margin: 19px 0px 0px 0px;
                /* top: 256.301px; */
                z-index: 3;
                width: 100%;
                line-height: 1.2em;
                display: inline-block;
            }
           

            .btn{
                background-color: rgb( 255, 255, 255 );
                position: relative;
                display: inline-block;
                width: 358px;
                padding: 5px;
                z-index: 5;
                font-size: 25px;
                margin:0 auto;
                color:#33cc99;
                text-decoration: none;
                margin-right: 10px
            }
            .right{
                float:right;
                width:60%;
            }
            
            hr{
                padding: 0;
                border: none;
                border-top: 5px solid #fff;
                color: #fff;
                text-align: center;
                margin: 0px auto;
                width: 420px;
                height:10px;
                z-index: -10;
            }
            
            hr:after {
                content: "\2022";
                display: inline-block;
                position: relative;
                top: -0.75em;
                font-size: 2em;
                padding: 0 0.2em;
                background: #33cc99;
            }
            
            .cloud {
                width: 350px; height: 120px;

                background: #FFF;
                background: linear-gradient(top, #FFF 100%);
                background: -webkit-linear-gradient(top, #FFF 100%);
                background: -moz-linear-gradient(top, #FFF 100%);
                background: -ms-linear-gradient(top, #FFF 100%);
                background: -o-linear-gradient(top, #FFF 100%);

                border-radius: 100px;
                -webkit-border-radius: 100px;
                -moz-border-radius: 100px;

                position: absolute;
                margin: 120px auto 20px;
                z-index:-1;
                transition: ease 1s;
            }

            .cloud:after, .cloud:before {
                content: '';
                position: absolute;
                background: #FFF;
                z-index: -1
            }

            .cloud:after {
                width: 100px; height: 100px;
                top: -50px; left: 50px;

                border-radius: 100px;
                -webkit-border-radius: 100px;
                -moz-border-radius: 100px;
            }

            .cloud:before {
                width: 180px; height: 180px;
                top: -90px; right: 50px;

                border-radius: 200px;
                -webkit-border-radius: 200px;
                -moz-border-radius: 200px;
            }
            
            .x1 {
                top:-50px;
                left:100px;
                -webkit-transform: scale(0.3);
                -moz-transform: scale(0.3);
                transform: scale(0.3);
                opacity: 0.9;
                -webkit-animation: moveclouds 15s linear infinite;
                -moz-animation: moveclouds 15s linear infinite;
                -o-animation: moveclouds 15s linear infinite;
            }
            
            .x1_5{
                top:-80px;
                left:250px;
                -webkit-transform: scale(0.3);
                -moz-transform: scale(0.3);
                transform: scale(0.3);
                -webkit-animation: moveclouds 17s linear infinite;
                -moz-animation: moveclouds 17s linear infinite;
                -o-animation: moveclouds 17s linear infinite; 
            }

            .x2 {
                left: 250px;
                top:30px;
                -webkit-transform: scale(0.6);
                -moz-transform: scale(0.6);
                transform: scale(0.6);
                opacity: 0.6; 
                -webkit-animation: moveclouds 25s linear infinite;
                -moz-animation: moveclouds 25s linear infinite;
                -o-animation: moveclouds 25s linear infinite;
            }

            .x3 {
                left: 250px; bottom: -70px;

                -webkit-transform: scale(0.6);
                -moz-transform: scale(0.6);
                transform: scale(0.6);
                opacity: 0.8; 

                -webkit-animation: moveclouds 25s linear infinite;
                -moz-animation: moveclouds 25s linear infinite;
                -o-animation: moveclouds 25s linear infinite;
            }

            .x4 {
                left: 470px; botttom: 20px;

                -webkit-transform: scale(0.75);
                -moz-transform: scale(0.75);
                transform: scale(0.75);
                opacity: 0.75;

                -webkit-animation: moveclouds 18s linear infinite;
                -moz-animation: moveclouds 18s linear infinite;
                -o-animation: moveclouds 18s linear infinite;
            }

            .x5 {
                left: 200px; top: 300px;

                -webkit-transform: scale(0.5);
                -moz-transform: scale(0.5);
                transform: scale(0.5);
                opacity: 0.8; 

                -webkit-animation: moveclouds 20s linear infinite;
                -moz-animation: moveclouds 20s linear infinite;
                -o-animation: moveclouds 20s linear infinite;
            }

            @-webkit-keyframes moveclouds {
                0% {margin-left: 1000px;}
                100% {margin-left: -1000px;}
            }
            @-moz-keyframes moveclouds {
                0% {margin-left: 1000px;}
                100% {margin-left: -1000px;}
            }
            @-o-keyframes moveclouds {
                0% {margin-left: 1000px;}
                100% {margin-left: -1000px;}
            }
    
    </style>

</head>
<body>


    <div id="clouds">
        <div class="cloud x1"></div>
        <div class="cloud x1_5"></div>
        <div class="cloud x2"></div>
        <div class="cloud x3"></div>
        <div class="cloud x4"></div>
        <div class="cloud x5"></div>
    </div>
    <div class='c'>
        <div class='_404'>404</div>
        <hr>
        <div class='_1'>THE PAGE</div>
        <div class='_2'>WAS NOT FOUND</div>
        <a class='btn' href="{% url 'disp:loginpage' %}" >Login Again</a>
    </div>
</body>

</html>

disp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

<style>


    * {
  box-sizing: border-box;
}

section {
  max-width: 770px;
  width: 100%;
  margin: 1rem auto;
  border: 1px solid lightgray;
  height: 630px;
  padding: 10px;
  padding-top: 67px;
}

.diagram {
  justify-content: center;
}

.flex {
  display: flex;
}

.align-center {
  align-items: center;
}

.space-between {
  justify-content: space-between;
}

.left, .right {
  flex: 1;
}

.left {
  margin-right: 60px;
}

.box {
  width: 150px;
  height: 75px;
  position: relative;
  box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.3);
  border: solid 1px #e8e8e8;
}

.margin-auto {
  margin: auto;
}

.one, .six {
  margin-bottom: 30px;
}

.three, .four {
  margin-bottom: 60px;
}

.box-16 {
  margin-bottom: 16px;
}

.box-mleft {
  margin-left: 76px;
}

.one::after, .six::after {
  background-color: #cacaca;
  position: absolute;
  content: '';
  height: 341px;
  width: 7px;
  top: 101%;
  left: 20px;
}

.six::after {
  height: 435.7px;
}

.three::after,
.five::after,
.eight::after,
.nine::after,
.ten::after,
.eleven::after,
.twolve::after {
  height: 7px;
  width: 34px;
  background-color: #cacaca;
  position: absolute;
  content: '';
  top: 50%;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  right: calc(100% + 15px);
}

.three::before,
.five::before,
.eight::before,
.nine::before,
.ten::before,
.eleven::before,
.twolve::before {
  content: '';
  position: absolute;
  top: 50%;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  right: 100%;
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 7.5px 0 7.5px 15px;
  border-color: transparent transparent transparent #cacaca;
}

.four::before {
  background-color: #cacaca;
  position: absolute;
  content: '';
  width: 7px;
  position: absolute;
  height: 45px;
  bottom: calc(100% + 15px);
  left: 50%;
  -webkit-transform: translateX(-50%);
          transform: translateX(-50%);
}

.four::after {
  position: absolute;
  content: '';
  left: 50%;
  -webkit-transform: translateX(-50%);
          transform: translateX(-50%);
  bottom: 100%;
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 15px 7.5px 0 7.5px;
  border-color: #cacaca transparent transparent transparent;
}

.two::after, .seven::after {
  background-color: #cacaca;
  position: absolute;
  content: '';
  left: 50%;
  -webkit-transform: translateX(-50%);
          transform: translateX(-50%);
  top: calc(100% + 15px);
  width: 7px;
  height: 330px;
}

.seven::after {
  height: 422px;
}

.two::before, .seven::before {
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 0 7.5px 15px 7.5px;
  border-color: transparent transparent #cacaca transparent;
  content: '';
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
          transform: translateX(-50%);
  top: 100%;
}

.box-inside {
  width: 100%;
  height: 100%;
}

.five .box-inside::after,
.four .box-inside::after,
.two .box-inside::after,
.eight .box-inside::after,
.nine .box-inside::after,
.ten .box-inside::after,
.eleven .box-inside::after,
.twolve .box-inside::after {
  background-color: #cacaca;
  position: absolute;
  content: '';
  height: 7px;
  width: 25px;
  top: 50%;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  left: 100%;
}

.two .box-inside::after {
  width: 45px;
}

.five .box-inside::before,
.four .box-inside::before,
.two .box-inside::before,
.eight .box-inside::before,
.nine .box-inside::before,
.ten .box-inside::before,
.eleven .box-inside::before,
.twolve .box-inside::before {
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 7.5px 0 7.5px 15px;
  border-color: transparent transparent transparent #cacaca;
  content: '';
  left: calc(100% + 25px);
  top: 50%;
  -webkit-transform: translateY(-50%);
          transform: translateY(-50%);
  position: absolute;
}

.two .box-inside::before {
  left: calc(100% + 45px);
}

.seven .box-inside::before {
  background-color: #cacaca;
  position: absolute;
  content: '';
  height: 45px;
  width: 7px;
  bottom: 100%;
  left: 50%;
  -webkit-transform: translateX(-50%);
          transform: translateX(-50%);
}

.seven .box-inside::after {
  background-color: #cacaca;
  position: absolute;
  content: '';
  height: 7px;
  width: 662px;
  bottom: calc(100% + 45px);
  right: 47%;
}

.one .box-inside::after {
  background-color: #cacaca;
  position: absolute;
  content: '';
  height: 30px;
  width: 7px;
  bottom: calc(100% + 15px);
  left: 14px;
}

.one .box-inside::before {
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 15px 7.5px 0 7.5px;
  border-color: #cacaca transparent transparent transparent;
  content: '';
  position: absolute;
  bottom: 100%;
  left: 10px;
}

header {
  text-transform: uppercase;
  text-align: center;
  font-size: 10px;
  background-color: greenyellow;
  font-weight: 600;
  padding: 2px 0;
}

.title {
  text-transform: uppercase;
  font-size: 9px;
  text-align: center;
  margin: 8px 0;
}

.number {
  text-align: center;
  font-size: 24px;
}

</style>

</head>
<body>
    <section>

        <div class="diagram flex">
     
    
         <div class="left">
          <div class="flex space-between">
              {% for table in colunms %}
           <div class="box one">
           
            <div class="box-inside">

             <header>
           
             </header>

                    <div class="body">
                      {% for c in table %}
                      <div class="title">{{c}}</div>
                      {% endfor %}
                
                    </div>
            </div>
           </div> {% endfor %}  
          
            
       
       </section>
</body>
</html>

disp/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Oracle</title>
	<meta charset="utf-8">

	<style type="text/css">
		body{
	margin:0;
 
 
	font:600 16px/18px 'Open Sans',sans-serif;
}
*,:after,:before{box-sizing:border-box}
.clearfix:after,.clearfix:before{content:'';display:table}
.clearfix:after{clear:both;display:block}
a{color:inherit;text-decoration:none}

.login-wrap{
	width:100%;
	margin:auto;
	max-width:525px;
	min-height:670px;
	position:relative;
 
	box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
}
.login-html{
	width:100%;
	height:100%;
	position:absolute;
	padding:90px 70px 50px 70px;
	background:rgba(77,77,77,.5);
}
.login-html .sign-in-htm,
.login-html .sign-up-htm{
	top:0;
	left:0;
	right:0;
	bottom:0;
	position:absolute;
 
	backface-visibility:hidden;
	transition:all .4s linear;
}
.login-html .sign-in,
.login-html .sign-up,
.login-form .group .check{
	display:none;
}
.login-html .tab,
.login-form .group .label,
.login-form .group .button{
	text-transform:uppercase;
}
.login-html .tab{
	font-size:22px;
	margin-right:15px;
	padding-bottom:5px;
	margin:0 15px 10px 0;
	display:inline-block;
	border-bottom:2px solid transparent;
}
.login-html .sign-in:checked + .tab,
.login-html .sign-up:checked + .tab{
	color:#fff;
	border-color:#1161ee;
}
.login-form{
	min-height:345px;
	position:relative;
	perspective:1000px;
	transform-style:preserve-3d;
}
.login-form .group{
	margin-bottom:15px;
}
.login-form .group .label,#t,#pass,
.login-form .group .input,
.login-form .group .button{
	width:100%;
	color:#fff;
	display:block;
}
.login-form .group .input,#t,#pass,
.login-form .group .button{
	border:none;
	padding:15px 20px;
	border-radius:25px;
	background:rgba(50,55,50,.1);
}
.login-form .group input[data-type="password"]{
	text-security:circle;
	-webkit-text-security:circle;
}
.login-form .group .label{
	color:#aaa;
	font-size:12px;
}
.login-form .group .button{
	background:rgba(22, 58, 126, 0.555);
}
.login-form .group label .icon{
	width:15px;
	height:15px;
	border-radius:2px;
	position:relative;
	display:inline-block;
	background:rgba(22, 58, 126, 0.555);
}
.login-form .group label .icon:before,
.login-form .group label .icon:after{
	content:'';
	width:10px;
	height:2px;
	background:#fff;
	position:absolute;
	transition:all .2s ease-in-out 0s;
}
.login-form .group label .icon:before{
	left:3px;
	width:5px;
	bottom:6px;
	transform:scale(0) rotate(0);
}
.login-form .group label .icon:after{
	top:6px;
	right:0;
	transform:scale(0) rotate(0);
}
.login-form .group .check:checked + label{
	color:#fff;
}
.login-form .group .check:checked + label .icon{
	background:#1161ee;
}
.login-form .group .check:checked + label .icon:before{
	transform:scale(1) rotate(45deg);
}
.login-form .group .check:checked + label .icon:after{
	transform:scale(1) rotate(-45deg);
}
.login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
	transform:rotate(0);
}
.login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
	transform:rotate(0);
}

.hr{
	height:2px;
	margin:60px 0 50px 0;
	background:rgba(22, 58, 126, 0.555);
}
.foot-lnk{
	text-align:center;
}
#feedback{
	text-align: center;
	color: red;
	display: none;
}

	</style>
</head>
<body>


	<div class="login-wrap">
	<div class="login-html">
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab"></label>
		<div class="login-form">
			<div class="sign-in-htm">
			<form method="POST">
				 
			{% csrf_token %}
			{{ form.as_p }}
			 
				<div class="group">
					<input type="submit"  class="button" value="Sign In">
				</div>
			</form>
				<div class="hr"></div>
				<div class="foot-lnk">
				 
					<br>
					<p> </p>
					<br>
			 
				</div>
			</div>

		</div>
	</div>
</div>

 

<!-- Comment out (or don't include) services that you don't want to use -->
<!-- <script src="https://www.gstatic.com/firebasejs/5.8.6/firebase-storage.js"></script> -->


 

</body>
</html>